[package]
name = "paranoia"
version = "0.1.0"
authors = ["aravix"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.2"
serde = { version = "1.0.201", features = ["derive"] }
toml = "0.8.12"
tui-textarea = "0.4.0"
